//! Pricing parity — priority-first best-price selection + modifier stack.
//!
//! The `parity_against_php_reference` test loads JSON scenarios generated by
//! `tests/scripts/generate-pricing-fixtures.php` and compares `compute_price` output against
//! the PHP reference values. Any divergence must be investigated before flipping
//! `productsProvider: rust` in production.
//!
//! Regenerate fixtures when `LiveProductsProvider::computeEffectivePrices` changes:
//! ```bash
//! php tests/scripts/generate-pricing-fixtures.php
//! ```

use std::sync::Arc;

use abel_products_daemon::{
	protocol::PriceModifiers,
	query::{
		pricing::{compute_effective_prices, compute_price},
		PricedProduct,
	},
	snapshot::{CatalogSnapshot, PriceFact, PriceFactFlags, PricelistIdx, PricelistMeta, ProductRow},
};
use roaring::RoaringBitmap;
use serde::Deserialize;
use smallvec::SmallVec;

#[derive(Debug, Deserialize)]
struct Fixture {
	scenarios: Vec<Scenario>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Scenario {
	id: String,
	description: String,
	input: ScenarioInput,
	expected: ScenarioExpected,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ScenarioInput {
	price: f64,
	/// PHP-side null collapses to `price` (tax-inclusive defaults to tax-exclusive). In
	/// production the Rust daemon sees the collapsed value via SQL `COALESCE(priceVat, price)`
	/// in `loaders.rs`; this test mirrors that in `compute_price_from_scenario`.
	price_vat: Option<f64>,
	price_before: f64,
	price_vat_before: f64,
	pricelist_allow_surcharge: bool,
	pricelist_allow_discount_level: bool,
	product_discount_level_pct: u8,
	modifiers: FixtureModifiers,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct FixtureModifiers {
	discount_level_pct: u8,
	max_product_discount_level: u8,
	surcharge_level_pct: f64,
	currency_rate: Option<f64>,
	calculation_precision: u8,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ScenarioExpected {
	price: f64,
	price_vat: f64,
	price_before: f64,
	price_vat_before: f64,
}

/// Acceptance: f64 arithmetic with `round_to_prec` on both sides should produce bit-identical
/// results. We allow 1e-9 tolerance for the edge case where PHP's `round` and Rust's f64
/// `round` diverge by one ULP on the scaled intermediate (extremely rare in practice).
const TOLERANCE: f64 = 1e-9;

#[test]
fn parity_against_php_reference() {
	let fixture_path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/pricing/golden.json");
	let bytes = std::fs::read(fixture_path).unwrap_or_else(|e| panic!("reading {fixture_path}: {e}"));
	let fixture: Fixture = serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("parsing {fixture_path}: {e}"));

	assert!(
		!fixture.scenarios.is_empty(),
		"fixture file at {fixture_path} is empty — run `php tests/scripts/generate-pricing-fixtures.php`"
	);

	let mut failures: Vec<String> = Vec::new();

	for scenario in &fixture.scenarios {
		let actual = compute_price_from_scenario(scenario);
		let expected = &scenario.expected;

		if let Err(msg) = compare_priced(&actual, expected) {
			failures.push(format!(
				"scenario {} ({}):\n  {}\n  rust: price={} priceVat={} priceBefore={} priceVatBefore={}\n  php:  price={} priceVat={} priceBefore={} priceVatBefore={}",
				scenario.id,
				scenario.description,
				msg,
				actual.price,
				actual.price_vat,
				actual.price_before,
				actual.price_vat_before,
				expected.price,
				expected.price_vat,
				expected.price_before,
				expected.price_vat_before,
			));
		}
	}

	if !failures.is_empty() {
		panic!(
			"{} of {} pricing scenarios diverged from PHP reference:\n\n{}",
			failures.len(),
			fixture.scenarios.len(),
			failures.join("\n\n")
		);
	}
}

fn compute_price_from_scenario(scenario: &Scenario) -> PricedProduct {
	let input = &scenario.input;

	// PriceFact storage is f64 (matches PHP double throughout the pipeline).
	// NULL priceVat collapses to `price` — same shape as `loaders.rs` SQL COALESCE.
	let hit = PriceFact::new(
		0,
		0,
		PriceFactFlags::empty(),
		input.price,
		input.price_vat.unwrap_or(input.price),
		input.price_before,
		input.price_vat_before,
	);
	let pricelist_meta = PricelistMeta {
		idx: 0,
		priority: 0,
		rate: 1.0,
		allow_discount_level: input.pricelist_allow_discount_level,
		allow_surcharge: input.pricelist_allow_surcharge,
		is_active: true,
	};
	let modifiers = PriceModifiers {
		discount_level_pct: input.modifiers.discount_level_pct,
		max_product_discount_level: input.modifiers.max_product_discount_level,
		surcharge_level_pct: input.modifiers.surcharge_level_pct,
		currency_rate: input.modifiers.currency_rate,
		calculation_precision: input.modifiers.calculation_precision,
	};

	compute_price(0, hit, pricelist_meta, input.product_discount_level_pct, &modifiers)
}

fn compare_priced(actual: &PricedProduct, expected: &ScenarioExpected) -> Result<(), String> {
	for (label, a, e) in [
		("price", actual.price, expected.price),
		("priceVat", actual.price_vat, expected.price_vat),
		("priceBefore", actual.price_before, expected.price_before),
		("priceVatBefore", actual.price_vat_before, expected.price_vat_before),
	] {
		let diff = (a - e).abs();
		if diff > TOLERANCE {
			return Err(format!("{label} diverged: |{a} - {e}| = {diff} > {TOLERANCE}"));
		}
	}
	Ok(())
}

// --- Pipeline tests -----------------------------------------------------------------------
//
// Smaller, hand-wired scenarios that exercise the non-math parts of the hot path:
// priority-first pricelist selection (the sort-order fix), hidden skip, and dropping products
// whose only pricelists are not in the customer's set. The parity suite covers `compute_price`
// in isolation; these tests cover the `compute_effective_prices` orchestration.

/// Build a snapshot with 2 products and 3 pricelists at varying priorities. Prices are crafted so
/// the "winner" depends on the priority-ASC rule and the `hidden` flag.
fn mini_snapshot() -> Arc<CatalogSnapshot> {
	// Pricelists pushed out of priority order on purpose — verifies the `sort_unstable_by_key`
	// in snapshot::build actually sorts by priority and doesn't rely on DB ordering.
	let pricelist_metas = vec![
		PricelistMeta {
			idx: 0,
			priority: 30,
			rate: 1.0,
			allow_discount_level: false,
			allow_surcharge: false,
			is_active: true,
		},
		PricelistMeta {
			idx: 1,
			priority: 10,
			rate: 1.0,
			allow_discount_level: false,
			allow_surcharge: false,
			is_active: true,
		},
		PricelistMeta {
			idx: 2,
			priority: 20,
			rate: 1.0,
			allow_discount_level: false,
			allow_surcharge: false,
			is_active: true,
		},
	];

	let products = vec![
		ProductRow {
			uuid_idx: 0,
			name: None,
			producer: None,
			display_amount: None,
			display_delivery: None,
			discount_level_pct: 0,
			is_project: false,
			is_master: true,
			project_ics: SmallVec::new(),
			attr_values: SmallVec::new(),
			ribbons: SmallVec::new(),
			internal_ribbons: SmallVec::new(),
		},
		ProductRow {
			uuid_idx: 1,
			name: None,
			producer: None,
			display_amount: None,
			display_delivery: None,
			discount_level_pct: 0,
			is_project: false,
			is_master: true,
			project_ics: SmallVec::new(),
			attr_values: SmallVec::new(),
			ribbons: SmallVec::new(),
			internal_ribbons: SmallVec::new(),
		},
	];

	// Prices, pre-sorted by (product, priority_asc) as `SnapshotBuilder` would produce.
	let prices = vec![
		// product 0, pl 1 (prio 10)
		PriceFact::new(0, 1, PriceFactFlags::empty(), 80.0, 96.8, 0.0, 0.0),
		// product 0, pl 2 (prio 20) — hidden; must be skipped even when pl 2 is in the customer set
		PriceFact::new(0, 2, PriceFactFlags::empty().with_hidden(true), 90.0, 108.9, 0.0, 0.0),
		// product 0, pl 0 (prio 30)
		PriceFact::new(0, 0, PriceFactFlags::empty(), 100.0, 121.0, 0.0, 0.0),
		// product 1, pl 2 (prio 20)
		PriceFact::new(1, 2, PriceFactFlags::empty(), 150.0, 181.5, 0.0, 0.0),
		// product 1, pl 0 (prio 30)
		PriceFact::new(1, 0, PriceFactFlags::empty(), 200.0, 242.0, 0.0, 0.0),
	];
	let prices_by_product = vec![0..3, 3..5];

	let mut snap = Arc::into_inner(CatalogSnapshot::empty()).expect("fresh Arc has a single owner");
	snap.products = products;
	snap.pricelists = pricelist_metas;
	snap.prices = prices;
	snap.prices_by_product = prices_by_product;
	Arc::new(snap)
}

fn neutral_modifiers() -> PriceModifiers {
	PriceModifiers::default()
}

fn mask_from(indexes: &[u32]) -> RoaringBitmap {
	indexes.iter().copied().collect()
}

/// Priority-first: given customer {pl0, pl1, pl2}, product 0 must pick pl1 (prio 10, lowest)
/// and product 1 must pick pl2 (prio 20, lowest after hidden/absent eliminations).
#[test]
fn priority_first_picks_lowest_priority_in_customer_set() {
	let snap = mini_snapshot();
	let mask = mask_from(&[0, 1]);
	let customer_pricelists: Vec<PricelistIdx> = vec![0, 1, 2];

	let priced =
		compute_effective_prices(&snap, &mask, &customer_pricelists, &neutral_modifiers()).expect("no daemon error");

	assert_eq!(priced.len(), 2, "both products must survive: {priced:?}");
	let by_product: std::collections::HashMap<u32, &PricedProduct> = priced.iter().map(|p| (p.product, p)).collect();

	let p0 = by_product[&0];
	assert_eq!(
		p0.pricelist, 1,
		"product 0 must pick pl1 (priority 10 wins over pl0 prio 30 and pl2 hidden)"
	);
	assert!((p0.price - 80.0).abs() < TOLERANCE, "expected 80.0, got {}", p0.price);

	let p1 = by_product[&1];
	assert_eq!(
		p1.pricelist, 2,
		"product 1 must pick pl2 (priority 20 wins over pl0 prio 30)"
	);
	assert!((p1.price - 150.0).abs() < TOLERANCE, "expected 150.0, got {}", p1.price);
}

/// Hidden pricelist must be skipped. Product 0's only non-hidden option in customer set {pl2}
/// is the hidden pl2 row itself — so product 0 is dropped from the result.
#[test]
fn hidden_price_row_is_skipped_and_product_dropped_when_no_other_option() {
	let snap = mini_snapshot();
	let mask = mask_from(&[0, 1]);
	let customer_pricelists: Vec<PricelistIdx> = vec![2];

	let priced =
		compute_effective_prices(&snap, &mask, &customer_pricelists, &neutral_modifiers()).expect("no daemon error");

	assert_eq!(
		priced.len(),
		1,
		"product 0 must be dropped — pl2 entry is hidden; product 1 survives with pl2. got: {priced:?}"
	);
	let survivor = &priced[0];
	assert_eq!(survivor.product, 1, "only product 1 survives with customer set {{pl2}}");
	assert_eq!(survivor.pricelist, 2);
}

/// Product without any pricelist match in the customer set is silently dropped (not returned
/// as priced with zero). In production this is also caught by `has_any_price_mask` earlier.
#[test]
fn product_without_matching_pricelist_is_dropped() {
	let snap = mini_snapshot();
	let mask = mask_from(&[0, 1]);
	// Customer set contains only pl 0 — product 0 can use it (prio 30, no hidden), but product 1 too.
	// Force a no-match scenario by shrinking customer set to a pricelist that exists in the
	// snapshot but neither product has a non-hidden entry for: pl 1 with a dummy idx.
	// Simpler approach: empty customer set → nothing survives.
	let customer_pricelists: Vec<PricelistIdx> = vec![];

	let priced =
		compute_effective_prices(&snap, &mask, &customer_pricelists, &neutral_modifiers()).expect("no daemon error");
	assert!(
		priced.is_empty(),
		"empty customer pricelist set must yield no priced products: {priced:?}"
	);
}

/// Modifiers stack with the priority-first pick: when pl1 allows discount and customer has a
/// global discount level, the pipeline applies it on top of the winning pricelist's price.
#[test]
fn modifiers_apply_to_priority_first_winner() {
	let mut snap = Arc::into_inner(mini_snapshot()).expect("unique owner");
	// Flip pl1 to allow discount — now the 10 % global discount should land on product 0's 80.0.
	snap.pricelists[1].allow_discount_level = true;
	let snap = Arc::new(snap);

	let mask = mask_from(&[0]);
	let customer_pricelists: Vec<PricelistIdx> = vec![0, 1, 2];
	let modifiers = PriceModifiers {
		discount_level_pct: 10,
		..PriceModifiers::default()
	};

	let priced = compute_effective_prices(&snap, &mask, &customer_pricelists, &modifiers).expect("no daemon error");
	assert_eq!(priced.len(), 1);
	let p = &priced[0];
	assert_eq!(
		p.pricelist, 1,
		"still picks pl1 (lowest priority), discount is applied *after* the pick"
	);
	// 80.0 * 0.9 = 72.0
	assert!(
		(p.price - 72.0).abs() < TOLERANCE,
		"discounted price: expected 72.0, got {}",
		p.price
	);
}

/// Sanity: `compute_price` called via the same shape as the fixture generator, using the mini
/// snapshot's pricelist metadata. Guards against regression where refactor of apply_modifiers
/// would decouple snapshot lookup from math in a silently-wrong way.
#[test]
fn compute_price_direct_call_stays_in_sync_with_pipeline() {
	let snap = mini_snapshot();
	let hit = snap.prices[0]; // product 0, pl 1, price 80.0
	let pricelist_meta = snap.pricelists[hit.pricelist as usize];
	let product_discount_pct = snap.products[hit.product as usize].discount_level_pct;

	let direct = compute_price(
		hit.product,
		hit,
		pricelist_meta,
		product_discount_pct,
		&neutral_modifiers(),
	);
	assert!((direct.price - 80.0).abs() < TOLERANCE);
	assert_eq!(direct.pricelist, 1);
}
